@Url = http://localhost:5084/users-module
@email = user1@confab.io
@password = secret
@role = user
@accessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNDJjMTMxNi05N2ZmLTQ3NzUtOWE5OS0wNWZmNzU1ZjM3ZjQiLCJ1bmlxdWVfbmFtZSI6ImE0MmMxMzE2LTk3ZmYtNDc3NS05YTk5LTA1ZmY3NTVmMzdmNCIsImp0aSI6IjhhYjlhZWM5LTMzOTItNGMzMy05ZmUyLTE2NGJkYjU1ZGY0ZSIsImlhdCI6IjE3MDU1MjM0MTAyNzgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiXSwibmJmIjoxNzA1NTIzNDEwLCJleHAiOjE3MDU1MjcwMTAsImlzcyI6ImNvbmZhYiJ9.spCJFZZwEppMklp-tAqt84Ze-33ylRgY5iA_jUsVGaJ39LFk3KazA7LzvNi2jPiVZ9M95dnmDy5b4mvGaOER4A

GET {{Url}}
Accept: application/json

###
GET {{Url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{Url}}/account/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "{{role}}",
    "claims": {
        "permissions": ["conferences", "hosts", "speakers", "users"]
    }
}

###
POST {{Url}}/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}