@Url = http://localhost:5084/users-module
@email = user1@confab.io
@password = secret
@role = user
@accessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNDJjMTMxNi05N2ZmLTQ3NzUtOWE5OS0wNWZmNzU1ZjM3ZjQiLCJ1bmlxdWVfbmFtZSI6ImE0MmMxMzE2LTk3ZmYtNDc3NS05YTk5LTA1ZmY3NTVmMzdmNCIsImp0aSI6IjFjZTA3NDVmLWU4ZmUtNDFkMC1iM2I3LTk5MjJmZjExOTc4NiIsImlhdCI6IjE3MDU2OTYxMjg4MTMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiXSwibmJmIjoxNzA1Njk2MTI4LCJleHAiOjE3MDU2OTk3MjgsImlzcyI6ImNvbmZhYiJ9.jxK5a7LbX7m0a2cM4G1mT2y_bmteqpvPjLe4XdqtL3Kzobm9RRtVoHNPlDrVuaJ_k0vAHIFzvI3OEclwSRs0nQ

GET {{Url}}
Accept: application/json

###
GET {{Url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{Url}}/account/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "{{role}}",
    "claims": {
        "permissions": ["conferences", "hosts", "speakers", "users"]
    }
}

###
POST {{Url}}/account/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}