@Url = http://localhost:5084/agendas-module


GET {{Url}}
Accept: application/json

@accessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNmI3YjgwMC01ZDgxLTRiYmYtOGQ5Yi1hNzlkMGNjY2IyZWYiLCJ1bmlxdWVfbmFtZSI6ImY2YjdiODAwLTVkODEtNGJiZi04ZDliLWE3OWQwY2NjYjJlZiIsImp0aSI6IjRhZWU0ZDczLTkwMzAtNDc1Ny1iZjY1LTZlMTIyNGI1OTI5NiIsImlhdCI6IjE3MDcxMzI0Mjk1MDUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiLCJhZ2VuZGFzIiwiY2ZwIiwic3VibWlzc2lvbnMiXSwibmJmIjoxNzA3MTMyNDI5LCJleHAiOjE3MDcxMzYwMjksImlzcyI6ImNvbmZhYiJ9.TerT1YXr7Wjq5CopC6YFsy7jfGv1oMDUcy_O8lPofEjGEmQIv2z_8bfB-qtI8y06NOpnPGxdRSllBiCyVl8aPA

@ConferenceId = b792bb9a-41df-4c30-9502-83cf15824ed8

###
POST {{Url}}/agendas/tracks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "conferenceId": "{{ConferenceId}}",
    "name": "Agenda track #3"
}

@TrackId = 9ba85f9e-6a12-4c38-ba8f-c57587d87271

###
GET {{Url}}/agendas/{{ConferenceId}}/tracks/{{TrackId}}
Accept: application/json

###
POST {{Url}}/agendas/{{ConferenceId}}/slots
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "agendaTrackId": "{{TrackId}}",
    "from": "2024-01-25T12:20:00",
    "to": "2024-01-25T13:50:00",
    "participantsLimit": 5,
    "type": "Regular"
}

###
@SlotId = 76a25bfa-d0d8-41e3-ac37-e4c7869f2a92

###
POST {{Url}}/conferences/{{ConferenceId}}/cfp
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "from": "2024-01-25T12:20:00",
    "to": "2024-01-25T13:50:00"
}

###
PUT {{Url}}/conferences/{{ConferenceId}}/cfp/open
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    
}

@SpeakerId = f6b7b800-5d81-4bbf-8d9b-a79d0cccb2ef

###
POST {{Url}}/submissions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "conferenceId": "{{ConferenceId}}",
    "title": "test submission3",
    "description": "this is description of test submission3",
    "level": 3,
    "tags": [
        "stationary",
        "dotnet"
    ],
    "speakerIds": [
        "{{SpeakerId}}"
    ]
}

###
@SubmissionId = a7075602-3de6-43db-80ed-cfdc933097cf

###
PUT {{Url}}/submissions/{{SubmissionId}}/approve
Authorization: Bearer {{accessToken}}

@AgendaItemId = a7075602-3de6-43db-80ed-cfdc933097cf


###
PUT {{Url}}/agendas/{{ConferenceId}}/slots/regular
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "agendaTrackId": "{{TrackId}}",
    "agendaSlotId": "{{SlotId}}",
    "agendaItemId": "{{AgendaItemId}}"
}