@Url = http://localhost:5084/conferences-module
@HostId = db140927-053d-40c0-a714-490113d50454

@accessToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNDJjMTMxNi05N2ZmLTQ3NzUtOWE5OS0wNWZmNzU1ZjM3ZjQiLCJ1bmlxdWVfbmFtZSI6ImE0MmMxMzE2LTk3ZmYtNDc3NS05YTk5LTA1ZmY3NTVmMzdmNCIsImp0aSI6IjBhZTEzZjc1LTBlM2EtNGI4Mi05YmQyLTYxZmY1MGQxN2UwZCIsImlhdCI6IjE3MDYwNDAzMzA1NzQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidXNlcnMiXSwibmJmIjoxNzA2MDQwMzMwLCJleHAiOjE3MDYwNDM5MzAsImlzcyI6ImNvbmZhYiJ9.ykBVagMtYtYM89IdxlqLJYJ-ptjutS80hGJIgENNSz3-vlLWEMtzT5_JX69Odx9WB_V9AptYxZEjGN-9KO3-YQ


GET {{Url}}
Accept: application/json

###### HOSTS ######

###
POST {{Url}}/hosts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Host #1",
    "description": "Lorem ipsum"
}

###
GET {{Url}}/hosts/{{HostId}}
Content-Type: application/json

###
GET {{Url}}/hosts
Content-Type: application/json

###
PUT {{Url}}/hosts/{{HostId}}
Content-Type: application/json

{
    "name": "Host #2",
    "conferences": [],
    "description": "Muspi merol"
}

###
DELETE {{Url}}/hosts/{{HostId}}
Authorization: Bearer {{accessToken}}

###### CONFERENCES ######

@ConferenceId = 877cc734-6c15-430c-accc-35ad84904141
###
POST {{Url}}/conferences
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Conference #1",
    "hostId": "{{HostId}}",
    "description": "Lorem ipsum",
    "logoUrl": "123",
    "hostName": "Some host",
    "location": "Warsaw",
    "from": "2024-01-20",
    "to": "2024-01-24",
    "participantLimit": 100
}

###
GET {{Url}}/conferences/{{ConferenceId}}
Content-Type: application/json

###
GET {{Url}}/conferences
Content-Type: application/json

###
PUT {{Url}}/conferences/{{ConferenceId}}
Content-Type: application/json

{
    "name": "Conference #2",
    "description": "Lorem ipsum",
    "logoUrl": "123",
    "hostName": "Some host",
    "location": "Warsaw",
    "from": "2024-01-09",
    "to": "2024-01-12",
    "participantLimit": 100
}

###
DELETE {{Url}}/conferences/{{ConferenceId}}