@Url = http://localhost:5084/speakers-module

@SpeakerId = a2d53452-a4a0-466c-a29f-a7ef87321041

GET {{Url}}
Accept: application/json

###
POST {{Url}}/speakers
Content-Type: application/json

{
    "bio": "Interesting John bio [...]",
    "email": "john.doe@confab.io",
    "fullName": "John Doe"
}

###
GET {{Url}}/speakers/{{SpeakerId}}


###
PUT {{Url}}/speakers/{{SpeakerId}}
Content-Type: application/json

{
    "bio": "more interesting John bio [...]",
    "email": "john.notdoe@confab.io",
    "fullName": "John Notdoe"
}

###
DELETE {{Url}}/speakers/{{SpeakerId}}